/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [1.34MB] > /Users/parksangyee/Desktop/project1/landing-page/public/models/butterfly1/scene-transformed.glb [21.59MB] (-1516%)
Author: dennissoderblom (https://sketchfab.com/dennissoderblom)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/butterfly-365ce4edd01f4a15ad0336f51588128a
Title: Butterfly
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Butterfly1(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/butterfly1/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Object_3">
          <group name="Object_6" position={[3.22, 0.013, 2.565]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Object_7" position={[26.986, 0, 0]}>
              <group name="MorphMainGroup">
                <mesh name="Wing_1_4" geometry={nodes.Wing_1_4.geometry} material={materials.Wing_1} />
              </group>
              <group name="MorphMainGroup_1">
                <mesh name="Wing_1_5" geometry={nodes.Wing_1_5.geometry} material={materials.Wing_1} />
              </group>
            </group>
            <group name="Object_12" position={[26.986, 0, 0]}>
              <group name="MorphMainGroup_2">
                <mesh name="Wing_1_6" geometry={nodes.Wing_1_6.geometry} material={materials.Wing_1} />
              </group>
              <group name="MorphMainGroup_3">
                <mesh name="Wing_1_7" geometry={nodes.Wing_1_7.geometry} material={materials.Wing_1} />
              </group>
            </group>
          </group>
          <group name="Object_17" position={[2.57, -0.137, 12.826]} rotation={[Math.PI, -0.049, 0]}>
            <group name="TimeframeMainGroup">
              <group name="Object_19">
                <mesh name="Cylinder001_7_0_1" geometry={nodes.Cylinder001_7_0_1.geometry} material={materials.Cylinder001} />
              </group>
            </group>
            <group name="TimeframeMainGroup_1">
              <group name="Object_22">
                <mesh name="Cylinder001_7_0_2" geometry={nodes.Cylinder001_7_0_2.geometry} material={materials.Cylinder001} />
              </group>
            </group>
          </group>
          <group name="Object_24" position={[1.182, 0, 4.719]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Object_25" position={[-29.375, 0, 0]}>
              <group name="MorphMainGroup_4">
                <mesh name="Line001_4" geometry={nodes.Line001_4.geometry} material={materials.Wing_1} />
              </group>
              <group name="MorphMainGroup_5">
                <mesh name="Line001_5" geometry={nodes.Line001_5.geometry} material={materials.Wing_1} />
              </group>
            </group>
            <group name="Object_30" position={[-29.375, 0, 0]}>
              <group name="MorphMainGroup_6">
                <mesh name="Line001_6" geometry={nodes.Line001_6.geometry} material={materials.Wing_1} />
              </group>
              <group name="MorphMainGroup_7">
                <mesh name="Line001_7" geometry={nodes.Line001_7.geometry} material={materials.Wing_1} />
              </group>
            </group>
          </group>
        </group>
        <mesh name="Cylinder001_7_0" geometry={nodes.Cylinder001_7_0.geometry} material={materials.Cylinder001} position={[2.57, -0.137, 12.826]} rotation={[Math.PI, -0.049, 0]} />
        <mesh name="Line001" geometry={nodes.Line001.geometry} material={materials.Wing_1} position={[-28.193, 0, 4.719]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Line001_1" geometry={nodes.Line001_1.geometry} material={materials.Wing_1} position={[-28.193, 0, 4.719]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Line001_2" geometry={nodes.Line001_2.geometry} material={materials.Wing_1} position={[-28.193, 0, 4.719]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Line001_3" geometry={nodes.Line001_3.geometry} material={materials.Wing_1} position={[-28.193, 0, 4.719]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Wing_1" geometry={nodes.Wing_1.geometry} material={materials.Wing_1} position={[30.205, 0.013, 2.565]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Wing_1_1" geometry={nodes.Wing_1_1.geometry} material={materials.Wing_1} position={[30.205, 0.013, 2.565]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Wing_1_2" geometry={nodes.Wing_1_2.geometry} material={materials.Wing_1} position={[30.205, 0.013, 2.565]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Wing_1_3" geometry={nodes.Wing_1_3.geometry} material={materials.Wing_1} position={[30.205, 0.013, 2.565]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/butterfly1/scene-transformed.glb')
