/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [47.02KB] > /Users/parksangyee/Desktop/project1/landing-page/public/models/phoenix./models/phoenix/scene-transformed.glb [263.05KB] (-459%)
Author: Sketchfab (https://sketchfab.com/Sketchfab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/real-time-bones-demo-phoenix-bird-6a8d1fd20a1f46e988d9d06e028f75a0
Title: Real-time Bones Demo: Phoenix Bird
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Phoenix(props) {
  const { nodes, materials } = useGLTF('./models/phoenix/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.MatI_Ride_FengHuang_01a} skeleton={nodes.Object_7.skeleton} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.MatI_Ride_FengHuang_01b} skeleton={nodes.Object_8.skeleton} />
    </group>
  )
}

useGLTF.preload('./models/phoenix/scene-transformed.glb')
