/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [105.31KB] > /Users/parksangyee/Desktop/project1/landing-page/public/models/yellow./models/yellow/scene-transformed.glb [257.85KB] (-145%)
Author: eb78 (https://sketchfab.com/E.A.Cornell)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/common-yellow-swallowtail-d9b1c6c813dc40829d7ebc8c7d65252a
Title: Common Yellow Swallowtail
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export function Yellow(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/yellow/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.fly.timeScale = 0.15
    actions.fly.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.CommonYellowSwallowtail} skeleton={nodes.Object_7.skeleton} scale={0.589} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/yellow/scene-transformed.glb')
